version: "3.9"
services:
    serverless:
        build:
            context: ./serverless
            args:
                - NODE_ENV=local
            dockerfile: Dockerfile
        ports:
            - "4900:8080"
    client:
        build:
            context: ./client
            args:
                - NODE_ENV=local
            dockerfile: Dockerfile
        ports:
            - "8080:80"
